name = "goldsolitu-de"
type = "webpack"
account_id = "281d53e37b5f5e67fd4effc6f20fd6e6"
#workers_dev = true
route = "https://goldsolitu.de/*"
zone_id = "1364386ab8d46d9766b6e3a699d4b2eb"

[site]
bucket = "./public"
entry-point = "workers-site"